version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cloud-backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: cloud-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: cloud-redis
    ports:
      - "6379:6379"